USE [master]
GO

/****** Object:  Database [Player]    Script Date: 04/23/2018 16:46:04 ******/
CREATE DATABASE [Player] ON  PRIMARY 
( NAME = N'Player', FILENAME = N'D:\Player.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Player_log', FILENAME = N'D:\Player_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Player] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Player].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Player] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Player] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Player] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Player] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Player] SET ARITHABORT OFF 
GO

ALTER DATABASE [Player] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Player] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Player] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Player] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Player] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Player] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Player] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Player] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Player] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Player] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Player] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Player] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Player] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Player] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Player] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Player] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Player] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Player] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Player] SET  READ_WRITE 
GO

ALTER DATABASE [Player] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Player] SET  MULTI_USER 
GO

ALTER DATABASE [Player] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Player] SET DB_CHAINING OFF 
GO

